services:
  app:
    build: .
    container_name: mattequiz_app
    volumes:
      - ./data:/data
    env_file: .env
    restart: unless-stopped
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
